language: python
dist: focal
python:
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -e .
  - pip install -r requirements_test.txt
script:
  - pylint --fail-under=9.9 pyotgw
  - pytest --cov --cov-report=term-missing
  - pre-commit run --all-files
